### ISSUE TITLE
/api/scripts/info/ needs authorisation

### ISSUE THREAD

**Issue by WilliamVenner** [DiscordStudios/gmodstore-issues#37]
For example,

/api/scripts/ needs an API key to show my script with script ID 1485 because it's denied.

/api/scripts/info/1485 doesn't need an API key to view information on script ID 1485.

**Comment by HandsomeMatt** [comment]
why

**Comment by WilliamVenner** [comment]
if there's no authorisation on /api/scripts/info/ then what's the point on having authorisation in /api/scripts

plus lapin is going through all the script ids lol

**Comment by Marcuzz** [comment]
you're actually dumb billy, /api/scripts doesn't need an API key, just a steamid. All supplying an API key there does is show denied scripts too

**Comment by WilliamVenner** [comment]
I'm not saying it needs authorisation specifically. It just _has_ authorisation. I'm fully aware you can just add a SteamID, and that's exactly my point - you can't see disabled or denied scripts if you don't provide an API key. The same should be for /api/scripts/info

**Comment by WilliamVenner** [comment]
I did, are you batshit retarded?

>/api/scripts/ needs an API key to **show my script with script ID 1485 because it's denied**.

**Comment by HandsomeMatt** [comment]
I still don't understand what you mean venner, your phrasing is so bad, what exactly do you want done

**Comment by WilliamVenner** [comment]
I'll be specific then

/api/scripts/info needs ?api_key and ?steamid arguments just like /api/scripts. /api/scripts/info can view information on scripts that cannot be seen in /api/scripts without supplying ?api_key.

**Comment by HandsomeMatt** [comment]
`/api/scripts/info can view information` like denied scripts? ok there we go, that's all the bug report had to be, thank u venner
