### ISSUE TITLE
When someone close a paypal dispute, notification telling us he opened one.

### ISSUE THREAD

**Issue by ExtReMLapin** [DiscordStudios/gmodstore-issues#50]
![](http://i.imgur.com/YyVBwZn.png)

Not the first time i got this when someone close a dispute.

**Comment by HandsomeMatt** [comment]
PayPal IPN doesn't give unique identifiers for open / closed cases. 3.0 (gmodstore) won't use PayPal as the payment gateway anyway so this'll no longer be applicable.
