### ISSUE TITLE
Adding /users/purchases/steam64 to API

### ISSUE THREAD

**Issue by Magelfik** [DiscordStudios/gmodstore-issues#51]
Adding a method in the user part of the API that allows to see what the user bought. This would of course be heavily restricted as it's private, but allowing an user to see what he bought via the API would be a good idea.

For example, calling via GET|POST /api/users/purchases/steam64 would return either a 403 (You can't see what another user has purchased) or 200 with every addon that the user bought.

**Comment by Magelfik** [comment]
Bump, this would really be practical.

**Comment by Marcuzz** [comment]
The next version of the site will have something like this. The current version will not however.
