### ISSUE TITLE
x3 notifications for 1 purchase

### ISSUE THREAD

**Issue by dothejason360** [DiscordStudios/gmodstore-issues#52]
for some reason i got 3 notifications for the same purchase
https://gyazo.com/db36cff7d5ab741434ffe3daabe228b5
https://gyazo.com/a6d6179ae993fba73150d6facbf5e8f4
im not sure if this is a bad thing but i just wanted to make sure im not paying 3 times lol

**Comment by ATomIK** [comment]
You're obviously not paying 3 times. It's just a miscommunication between PayPal and SF. PayPal's fault.

**Comment by dothejason360** [comment]
yea i figured... just thought i would ask and make sure you guys were aware of the issue... thanks for the reply :)
