### ISSUE TITLE
Still could not use chinese paypal account to purchase any addons

### ISSUE THREAD

**Issue by takaqiao** [DiscordStudios/gmodstore-issues#55]
I tried two cards
And It only says We can't process your payment right now, so please try again later. We're sorry for the inconvenience after clicking the purchase buttom(after choosing bank card)
I only can use balance to pay but i cannot transfer money to balance in paypal so it sucks

**Comment by Marcuzz** [comment]
We can't do anything about this at this point in time.

**Comment by takaqiao** [comment]
I dont undestand. Why?

**Comment by HandsomeMatt** [comment]
Because this is a PayPal issue, we only accept PayPal balance transfers and can't accept a direct payment from your card. You need to transfer money to your PayPal first and then purchase addons.

**Comment by takaqiao** [comment]
But u know theres not a buttom i can transfer my money to paypal balance
And i already paid 800USD in this website So plz help me to solve this problem..

**Comment by HandsomeMatt** [comment]
We can't help you solve this problem. This is an issue between you and PayPal sorry.

**Comment by takaqiao** [comment]
kk

**Comment by takaqiao** [comment]
Um... I still cant purchase any addons
But
I could purchase other things from other websites and pay the money directly
So i dont think its a problem between me and paypal
